### ISSUE TITLE
Scroll up to dismiss 'post-preview' 

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#95] opened 2020-07-09 08:29 UTC
so right now when you expand a post from a comment in the notification you have to scroll all the way down to read the comment and then you have to scroll all the way back up to click on 'x' to dismiss it. 

what if we just implement a 'strong swipe up' to dismiss the preview?

**Comment by Novusphere** [comment] 2020-07-09 13:49
duplicate of #59 "strong swipe" is a native feature, afaik not something that can be done on website or you would have to give an example of a website that does this @bluabaleno

**Closed by Novusphere** 2020-07-09 13:49 UTC
Labels: enhancement
