### ISSUE TITLE
TLOS logo does not trigger tag pop-up.

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#276] opened 2020-11-08 22:45 UTC
Current behavior 
<img width="859" alt="Screen Shot 2020-11-08 at 10 45 04 PM" src="https://user-images.githubusercontent.com/14120416/98486245-1ad83780-2214-11eb-9fa3-2d63b8564876.png">

Expected behavior 
<img width="859" alt="Screen Shot 2020-11-08 at 10 45 11 PM" src="https://user-images.githubusercontent.com/14120416/98486252-2297dc00-2214-11eb-963b-2bee26026cb4.png">

**Comment by xia256** [comment] 2020-11-08 22:46
duplicate of #274

**Closed by xia256** 2020-11-08 22:46 UTC
Labels: bug
