### ISSUE TITLE
Change how single post show and new login process

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-vue#58] opened 2020-07-03 21:17 UTC
[Google doc link ](https://docs.google.com/document/d/1yDFaMgARmMFdRfOlfCSUqL_g_zN06QaIbzW-Ai_QJQU/edit)

**Comment by Novusphere** [comment] 2020-07-05 03:53
The single post change has been made, regarding

> probably should have a bit of text that says "Don't have an EOS account?" somewhere that redirects them to the EOS account creation page.

this seems like a bad idea. If it's a new account and they don't have an EOS account, how are they going to create one? This only will confuse the user.

**Comment by bluabaleno** [comment] 2020-07-06 10:04
hmmm yeah that's a good point

**Comment by bluabaleno** [comment] 2020-07-22 11:44
bump

**Comment by Novusphere** [comment] 2020-08-20 23:01
Closed, duplicate of #75

**Closed by Novusphere** 2020-08-20 23:01 UTC
Labels: request
